name: rusty_ffi
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Sach97 <sacha.arbonel@hotmail.fr>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  ffi: ^0.1.3

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
